eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9010
 
spring:
  application:
    name: borrowService
  config:
    import: optional:configserver:http://localhost:8888
