eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
server:
  port: 9030
 
spring:
  application:
    name: notificationService
  config:
    import: optional:configserver:http://localhost:8888
